### ISSUE TITLE
Pip install consistently fails

### ISSUE THREAD

**Issue by abraxous** [NatTupper/dline#10]
`sudo pip3.7 install --user --process-dependency-link dline` consistently fails and returns the following stderr:

`Collecting dline
  Using cached https://files.pythonhosted.org/packages/33/73/a4d1363744a1cba03803fbdfe7a2e2449bb625a530c76c129e3088dfd9dc/dline-2.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8xnu0mlg/dline/setup.py", line 11, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8xnu0mlg/dline/
`

I have attempted this with pip3 as well as pip3.7. I am running Debian 9 Stretch and have python 3.7 installed separately.

**Comment by NatTupper** [comment]
Ah. I see the problem. Will post a fix soon.

**Comment by abraxous** [comment]
Very close. It's asking for discord.py==1.0.0a which is not among pip's available versions.

**Comment by abraxous** [comment]
Was able to complete install
