### ISSUE TITLE
A lot of messages don't show up in dline. 

### ISSUE THREAD

**Issue by Alumniminium** [NatTupper/dline#11]
Not sure why, but dline keeps missing messages. 
I was using dline for a couple of days now, and every couple minutes, messages are lost. 

I verified that by running dline and the official client, official client shows all incomming messages just fine, dline misses half of them.

**Comment by JushBJJ2** [comment]
Try to say "/update" to manually update the client.

**Comment by NatTupper** [comment]
This is an issue I have known about for some time now. I have not seen it myself but I will try to replicate and fix the issue. All `/update` does is refresh the screen based on current data. It's a debugging feature. If this fixes the problem though, please say so. That means it's a relatively easy fix, though I doubt that's the issue.

**Comment by Alumniminium** [comment]
Yea, /update obviously didn't work, I checked the code myself and I don't see anything obvious, I dont know how to debug python though, so I can't help. I'm a C# dev :/

**Comment by Alumniminium** [comment]
any updates? I'm getting too frustrated with dline to continue using it. I'll be looking for another CLI client otherwise.. :(

**Comment by NatTupper** [comment]
Sorry for the wait. I understand if you wish to use another client. I'll look into the issues that are open at the present time including this one.

**Comment by Alumniminium** [comment]
I'll get dline setup tonight and will let you know asap :)

Edit: Let it run overnight and didn't lose any messages yet..

**Comment by NatTupper** [comment]
I have reproduced the bug on my end. There's nothing that shows up in the debug log. I'll see if I can find out what's causing it.
