### ISSUE TITLE
Startup error message

### ISSUE THREAD

**Issue by DailytheNoob** [NatTupper/dline#12]
I installed dline through the first listed method. When I start dline by running the command `dline`, it says the following:
```
Error: client not started from repo location! Cancelling...
You must start the client from its folder to get automatic updates.

Starting...
```

it works fine after that, just wondering why it does that.

**Comment by Th3-Hum4n** [comment]
When dline starts, it updates itself using git. When you don't start it from the source's directory, it logs the above warning message.

**Comment by NatTupper** [comment]
I plan to remove this message when dline is installed rather than run from the repo directory. I consider this a bug and will try to fix it when I get around to it.

**Comment by NatTupper** [comment]
Commit 36e10c4d9777fe298bf3c624998aa1a1196fb755 fixes this bug.
