### ISSUE TITLE
dline crashes and hangs on startup

### ISSUE THREAD

**Issue by neeeeeem** [NatTupper/dline#15]
I don't really know what I'm doing when it comes to reporting issues, so apologies about that
### What I did:
- Installed dline using pip3, I'm using python version 3.7
- looked for discord token following the guide on the readme, pretty dang sure the token is right
- set token using --copy-token, error tells me that I have an unclosed client session (`client_session: <aiohttp.client.ClientSession object at 0x7f944cbaabe0>`, this has been in a lot of issues)
- ignored error, then proceeded to copy skeleton over using --copy-skeleton, same error again
- ran dline with `$ dline`, hangs a bit, cpu usage spikes, then an error occurs:
```Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/dline/__main__.py", line 100, in on_ready
    gc.client.set_current_guild(gc.settings["default_guild"])
  File "/home/user/.local/lib/python3.7/site-packages/dline/client/client.py", line 108, in set_current_guild
    if guild.lower() in gld.name.lower():
AttributeError: 'NoneType' object has no attribute 'lower'
```
- after that it just hangs, had to press ctrl-C a few times to get it to stop

**Comment by JushBJJ** [comment]
Change your default guild in the config file or join the dline discord:
https://discord.gg/gzaXm2

**Comment by NatTupper** [comment]
This seems to be a `default_guild` problem. Basically it's what @JushBJJ is saying. You need to change the `default_guild` setting to the name of the guild you want dline to start in by default. The `default_guild` option will be made optional in future versions, but for now it's a required setting. If this issue persists, please re-open the issue.
