### ISSUE TITLE
Attempting to switch to an ignored channel causes a freeze

### ISSUE THREAD

**Issue by blee5** [NatTupper/dline#16]
OS: Linux/Debian
Terminal: Bash
Python Version: 3.6.7

How to reproduce:
Ignore a channel in `channel_ignore_list`, attempt to switch to it using `/channel`

dline will freeze, and will periodically print error messages. Here's an example:
```
Traceback (most recent call last):
File "/home/void/.local/lib/python3.6/site-packages/discord/client.py", line 227, in _run_event
await coro(*args, **kwargs)
File "/home/void/dline/dline/__main__.py", line 144, in on_message_edit
ft = gc.ui.views[str(clog.id)].formattedText
KeyError: '518249820557934666'
```

**Comment by NatTupper** [comment]
Will look into.

**Comment by NatTupper** [comment]
Confirmed. Adding to major bugs since it causes a crash.
