### ISSUE TITLE
dline freezes when "/dm" command is called

### ISSUE THREAD

**Issue by JushBJJ** [NatTupper/dline#17]
Python Version: Python3.6
Terminal: uxrvt
Shell: bash

When I type in the command 

> /dm

or 
> /guild Private Messages 

Or anything similar freezes dline, and the issue is on the Mee6 bot which is quite weird for it to effect dline like that. A few months back me and Nat did a little test on reproducing the freeze. But it seems Nat's dm works even with mee6 on it.

**Comment by NatTupper** [comment]
Will look into

**Comment by NatTupper** [comment]
Tested and could not reproduce. Closing for now. If you have another method to reproduce, reopen the issue.
